/**
 * Built-in message definitions for ROS 2 actions and the Nav2 services iViz
 * calls, matching ROS 2 Jazzy.
 *
 * foxglove_bridge normally sends every definition at runtime and iViz prefers
 * those. These copies are used when a bridge advertises a service without a
 * schema, and by the mock bridge, which has no ROS to read them from.
 *
 * A ROS 2 action `pkg/action/Name` is carried by three hidden services and
 * two hidden topics, all generated by rosidl:
 *
 *   <action>/_action/send_goal    pkg/action/Name_SendGoal    { goal_id, goal } -> { accepted, stamp }
 *   <action>/_action/get_result   pkg/action/Name_GetResult   { goal_id } -> { status, result }
 *   <action>/_action/cancel_goal  action_msgs/srv/CancelGoal
 *   <action>/_action/feedback     pkg/action/Name_FeedbackMessage { goal_id, feedback }
 *   <action>/_action/status       action_msgs/msg/GoalStatusArray
 */

const SEP = "\n================================================================================\n";

/** Shared dependency blocks, keyed by their collapsed `pkg/Type` name. */
const BLOCKS: Record<string, string> = {
  "unique_identifier_msgs/UUID": "uint8[16] uuid",
  "std_msgs/Header": "builtin_interfaces/Time stamp\nstring frame_id",
  "std_msgs/String": "string data",
  // rosidl gives empty messages one dummy byte, and CDR carries it.
  "std_msgs/Empty": "uint8 structure_needs_at_least_one_member",
  "geometry_msgs/Point": "float64 x\nfloat64 y\nfloat64 z",
  "geometry_msgs/Quaternion": "float64 x 0\nfloat64 y 0\nfloat64 z 0\nfloat64 w 1",
  "geometry_msgs/Pose": "geometry_msgs/Point position\ngeometry_msgs/Quaternion orientation",
  "geometry_msgs/PoseStamped": "std_msgs/Header header\ngeometry_msgs/Pose pose",
  "nav_msgs/Path": "std_msgs/Header header\ngeometry_msgs/PoseStamped[] poses",
  "action_msgs/GoalInfo": "unique_identifier_msgs/UUID goal_id\nbuiltin_interfaces/Time stamp",
  "action_msgs/GoalStatus": "action_msgs/GoalInfo goal_info\nint8 status",
  "nav2_msgs/MissedWaypoint": "uint32 index\ngeometry_msgs/PoseStamped goal\nuint16 error_code",
};

/**
 * Concatenate a top-level definition with every block it references,
 * transitively and without duplicates. `builtin_interfaces/*` are primitives
 * to the parser and need no block.
 */
function build(top: string, local: Record<string, string> = {}): string {
  const all: Record<string, string> = { ...BLOCKS, ...local };
  const parts = [top];
  const seen = new Set<string>();
  const visit = (text: string): void => {
    for (const line of text.split("\n")) {
      const m = /^\s*([A-Za-z0-9_]+\/[A-Za-z0-9_]+)(?:\[[^\]]*\])?\s+[a-z]/.exec(line);
      if (!m) continue;
      const type = m[1]!;
      const body = all[type];
      if (body === undefined || seen.has(type)) continue;
      seen.add(type);
      parts.push(`MSG: ${type}\n${body}`);
      visit(body);
    }
  };
  visit(top);
  return parts.join(SEP);
}

interface ActionParts {
  goal: string;
  result: string;
  feedback: string;
}

const NAV_FEEDBACK = `geometry_msgs/PoseStamped current_pose
builtin_interfaces/Duration navigation_time
builtin_interfaces/Duration estimated_time_remaining
int16 number_of_recoveries
float32 distance_remaining`;

const NAV_RESULT = "uint16 error_code\nstring error_msg";

/** Jazzy definitions of the Nav2 actions iViz drives. */
const ACTIONS: Record<string, ActionParts> = {
  "nav2_msgs/action/NavigateToPose": {
    goal: "geometry_msgs/PoseStamped pose\nstring behavior_tree",
    result: NAV_RESULT,
    feedback: NAV_FEEDBACK,
  },
  "nav2_msgs/action/NavigateThroughPoses": {
    goal: "geometry_msgs/PoseStamped[] poses\nstring behavior_tree",
    result: NAV_RESULT,
    feedback: `${NAV_FEEDBACK}\nint16 number_of_poses_remaining`,
  },
  "nav2_msgs/action/FollowWaypoints": {
    goal: "uint32 number_of_loops\nuint32 goal_index\ngeometry_msgs/PoseStamped[] poses",
    result: `nav2_msgs/MissedWaypoint[] missed_waypoints\n${NAV_RESULT}`,
    feedback: "uint32 current_waypoint",
  },
  "nav2_msgs/action/FollowPath": {
    goal: "nav_msgs/Path path\nstring controller_id\nstring goal_checker_id\nstring progress_checker_id",
    result: `std_msgs/Empty result\n${NAV_RESULT}`,
    feedback: "float32 distance_to_goal\nfloat32 speed",
  },
};

export interface ActionSchemas {
  sendGoalRequest: string;
  sendGoalResponse: string;
  getResultRequest: string;
  getResultResponse: string;
  feedbackMessage: string;
}

/**
 * Schemas for the hidden services and feedback topic of a known action type.
 *
 * `nested` follows rosidl: `{ goal_id, goal: {...} }`. `flat` is how
 * foxglove_bridge describes the same types: the goal, result and feedback
 * fields sit next to `goal_id` / `status`. Both encode to identical bytes.
 */
export function actionSchemas(actionType: string, layout: "nested" | "flat" = "nested"): ActionSchemas | undefined {
  const parts = ACTIONS[actionType];
  if (!parts) return undefined;
  if (layout === "flat") {
    return {
      sendGoalRequest: build(`unique_identifier_msgs/UUID goal_id\n${parts.goal}`),
      sendGoalResponse: "bool accepted\nbuiltin_interfaces/Time stamp",
      getResultRequest: build("unique_identifier_msgs/UUID goal_id"),
      getResultResponse: build(`int8 status\n${parts.result}`),
      feedbackMessage: build(`unique_identifier_msgs/UUID goal_id\n${parts.feedback}`),
    };
  }
  const short = actionType.replace("/action/", "/");
  const local = {
    [`${short}_Goal`]: parts.goal,
    [`${short}_Result`]: parts.result,
    [`${short}_Feedback`]: parts.feedback,
  };
  return {
    sendGoalRequest: build(`unique_identifier_msgs/UUID goal_id\n${short}_Goal goal`, local),
    sendGoalResponse: "bool accepted\nbuiltin_interfaces/Time stamp",
    getResultRequest: build("unique_identifier_msgs/UUID goal_id"),
    getResultResponse: build(`int8 status\n${short}_Result result`, local),
    feedbackMessage: build(`unique_identifier_msgs/UUID goal_id\n${short}_Feedback feedback`, local),
  };
}

export const KNOWN_ACTION_TYPES = Object.keys(ACTIONS);

export const GOAL_STATUS_ARRAY = build("action_msgs/GoalStatus[] status_list");

export interface ServiceSchemas {
  request: string;
  response: string;
}

const SERVICES: Record<string, ServiceSchemas> = {
  "action_msgs/srv/CancelGoal": {
    request: build("action_msgs/GoalInfo goal_info"),
    response: build("int8 return_code\naction_msgs/GoalInfo[] goals_canceling"),
  },
  "nav2_msgs/srv/ManageLifecycleNodes": { request: "uint8 command", response: "bool success" },
  "nav2_msgs/srv/SaveMap": {
    request: "string map_topic\nstring map_url\nstring image_format\nstring map_mode\nfloat32 free_thresh\nfloat32 occupied_thresh",
    response: "bool result",
  },
  "slam_toolbox/srv/SaveMap": { request: build("std_msgs/String name"), response: "int8 result" },
};

/**
 * Request and response schemas for a service type iViz knows, including the
 * `_SendGoal` / `_GetResult` services generated for the actions above.
 */
export function fallbackServiceSchemas(serviceType: string): ServiceSchemas | undefined {
  const direct = SERVICES[serviceType];
  if (direct) return direct;
  const m = /^(.*)_(SendGoal|GetResult)$/.exec(serviceType);
  if (!m) return undefined;
  const a = actionSchemas(m[1]!);
  if (!a) return undefined;
  return m[2] === "SendGoal" ? { request: a.sendGoalRequest, response: a.sendGoalResponse } : { request: a.getResultRequest, response: a.getResultResponse };
}
